name: Run Unit tests
on: [push]
jobs:
  StaticCodeChecking:
    runs-on: ubuntu-latest
    steps:
      - run: echo "all is fine"
  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: x64
      - name: Compile it
        run: mvn compile
      - name: Start my unit tests
        run: mvn test
